[scheduler]
readiness-scheduler-01 ansible_connection=local

[workers]
readiness-worker-01 ansible_connection=local
readiness-worker-02 ansible_connection=local

[artifact_store]
readiness-artifacts-01 ansible_connection=local

[monitor]
readiness-monitor-01 ansible_connection=local
